import Head from 'next/head'


function Home() {
    return (
        <div>
            <Head>
                <title>ImageStock</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <footer>
            </footer>
        </div>
    )
}

export default Home;
